# Training Neural Networks

The network we built in the previous part isn't so smart, it doesn't know anything about our handwritten digits. Neural networks with non-linear activations work like universal function approximators. There is some function that maps our input to the output. For example, images of handwritten digits to class probabilities. The power of neural networks is that we can train them to approximate this function, and basically any function given enough data and compute time.

At first the network is naive, it doesn't know the function mapping the inputs to the outputs. We train the network by showing it examples of real data, then adjusting the network parameters such that it approximates this function.

To find these parameters, we need to know how poorly the network is predicting the real outputs. For this we calculate a **loss function** (also called the cost), a measure of our prediction error. For example, the mean squared loss is often used in regression and binary classification problems

$$
\ell = \frac{1}{2n}\sum_i^n{\left(y_i - \hat{y}_i\right)^2}
$$

where $n$ is the number of training examples, $y_i$ are the true labels, and $\hat{y}_i$ are the predicted labels.

By minimizing this loss with respect to the network parameters, we can find configurations where the loss is at a minimum and the network is able to predict the correct labels with high accuracy. We find this minimum using a process called **gradient descent**. The gradient is the slope of the loss function and points in the direction of fastest change. To get to the minimum in the least amount of time, we then want to follow the gradient (downwards). We can think of this like descending a mountain by following the steepest slope to the base.

## Backpropagation

For single layer networks, gradient descent is simple to implement. However, it's more complicated for deeper, multilayer neural networks like the one we've built. Complicated enough that it took about 30 years before researchers figured out how to train multilayer networks, although it's straightforward once you learn about it. 

This is done through **backpropagation** which is really just an application of the chain rule from calculus.

In the forward pass through the network, our data and operations go from right to left here. To train the weights with gradient descent, we propagate the gradient of the cost backwards through the network. Mathematically, this is really just calculating the gradient of the loss with respect to the weights using the chain rule.

$$
\frac{\partial \ell}{\partial w_1} = \frac{\partial l_1}{\partial w_1} \frac{\partial s}{\partial l_1} \frac{\partial l_2}{\partial s} \frac{\partial \ell}{\partial l_2}
$$

We update our weights using this gradient with some learning rate $\alpha$. 

$$
w^\prime = w - \alpha \frac{\partial \ell}{\partial w}
$$

The learning rate is set such that the weight update steps are small enough that the iterative method settles in a minimum.

The first thing we need to do for training is define our loss function. In PyTorch, you'll usually see this as `criterion`. Here we're using softmax output, so we want to use `criterion = nn.CrossEntropyLoss()` as our loss. Later when training, you use `loss = criterion(output, targets)` to calculate the actual loss.

We also need to define the optimizer we're using, SGD or Adam, or something along those lines. Here we'll just use SGD with `torch.optim.SGD`, passing in the network parameters and the learning rate.

## Autograd

Torch provides a module, `autograd`, for automatically calculating the gradient of tensors. It does this by keeping track of operations performed on tensors. To make sure PyTorch keeps track of operations on a tensor and calculates the gradients, we need to set `requires_grad` on a tensor. We can do this at creation with the `requires_grad` keyword, or at any time with `x.requires_grad_(True)`.

We can turn off gradients for a block of code with the `torch.no_grad()` content:
```python
x = torch.zeros(1, requires_grad=True)
>>> with torch.no_grad():
...     y = x * 2
>>> y.requires_grad
False
```

Also, we can turn on or off gradients altogether with `torch.set_grad_enabled(True|False)`.

The gradients are computed with respect to some variable `z` with `z.backward()`. This does a backward pass through the operations that created `z`.

In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

from collections import OrderedDict

import numpy as np
import time

import torch
from torch import nn
from torch import optim
import torch.nn.functional as F

import helper

In [2]:
x = torch.randn(2,2, requires_grad=True)
print(x)

tensor([[-0.1350, -1.7792],
        [-0.4889, -1.5319]])


In [3]:
y = x**2
print(y)

tensor([[ 0.0182,  3.1656],
        [ 0.2391,  2.3467]])


Below we can see the operation that created `y`, a power operation `PowBackward0`.

In [4]:
## grad_fn shows the function that generated this variable
print(y.grad_fn)

The autgrad module keeps track of these operations and knows how to calculate the gradient for each one. In this way, it's able to calculate the gradients for a chain of operations, with respect to any one tensor. Let's reduce the tensor `y` to a scalar value, the mean.

In [5]:
z = y.mean()
print(z)

tensor(1.4424)


We can check the gradients for `x` and `y` but they are empty currently.

In [6]:
print(x.grad)

None


To calculate the gradients, we need to run the `.backward` method on a Variable, `z` for example. This will calculate the gradient for `z` with respect to `x`

$$
\frac{\partial z}{\partial x} = \frac{\partial}{\partial x}\left[\frac{1}{n}\sum_i^n x_i^2\right] = \frac{x}{2}
$$

In [7]:
z.backward()
print(x.grad)
print(x/2)

tensor([[-0.0675, -0.8896],
        [-0.2445, -0.7660]])
tensor([[-0.0675, -0.8896],
        [-0.2445, -0.7660]])


These gradients calculations are particularly useful for neural networks. For training we need the gradients of the weights with respect to the cost. With PyTorch, we run data forward through the network to calculate the cost, then, go backwards to calculate the gradients with respect to the cost. Once we have the gradients we can make a gradient descent step. 

## Get the data and define the network

We'll load the MNIST dataset and define our network.

In [8]:
from torchvision import datasets, transforms

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                             ])
# Download and load the training data
trainset = datasets.MNIST('MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

Processing...
Done!


We'll build a network with `nn.Sequential` here. Only difference from the last part is we are not actually using softmax on the output, but instead just using the raw output from the last layer. This is because the output from softmax is a probability distribution. Often, the output will have values really close to zero or really close to one. Due to [inaccuracies with representing numbers as floating points](https://docs.python.org/3/tutorial/floatingpoint.html), computations with a softmax output can lose accuracy and become unstable. To get around this, we'll use the raw output, called the **logits**, to calculate the loss.

In [9]:
# Hyperparameters for our network
input_size = 784
hidden_sizes = [128, 64]
output_size = 10

# Build a feed-forward network
model = nn.Sequential(OrderedDict([
                      ('fc1', nn.Linear(input_size, hidden_sizes[0])),
                      ('relu1', nn.ReLU()),
                      ('fc2', nn.Linear(hidden_sizes[0], hidden_sizes[1])),
                      ('relu2', nn.ReLU()),
                      ('logits', nn.Linear(hidden_sizes[1], output_size))]))

## Training the network!

The first thing we need to do for training is define our loss function. In PyTorch, we'll usually see this as `criterion`. Here we're using softmax output, so we want to use `criterion = nn.CrossEntropyLoss()` as our loss. Later when training, we use `loss = criterion(output, targets)` to calculate the actual loss.

We also need to define the optimizer we're using, SGD or Adam, or something along those lines. Here we'll just use SGD with `torch.optim.SGD`, passing in the network parameters and the learning rate.

In [10]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

First, let's consider just one learning step before looping through all the data. The general process with PyTorch:

* Make a forward pass through the network to get the logits 
* Use the logits to calculate the loss
* Perform a backward pass through the network with `loss.backward()` to calculate the gradients
* Take a step with the optimizer to update the weights

Below we'll go through one training step and print out the weights and gradients so you can see how it changes.

In [11]:
print('Initial weights - ', model.fc1.weight)

images, labels = next(iter(trainloader))
images.resize_(64, 784)

# Clear the gradients, do this because gradients are accumulated
optimizer.zero_grad()

# Forward pass, then backward pass, then update weights
output = model.forward(images)
loss = criterion(output, labels)
loss.backward()
print('Gradient -', model.fc1.weight.grad)
optimizer.step()

Initial weights -  Parameter containing:
tensor([[ 7.0399e-03, -2.5535e-02, -8.3050e-03,  ..., -4.6199e-03,
         -3.0042e-02,  2.6735e-02],
        [ 2.7560e-02, -2.4557e-02, -3.5584e-02,  ...,  7.0224e-03,
          2.2178e-02, -1.2602e-02],
        [ 2.9504e-04, -2.6209e-02, -2.0014e-02,  ...,  7.5640e-03,
         -2.0669e-02, -1.4529e-02],
        ...,
        [-2.4984e-02, -2.6639e-02, -7.7125e-03,  ..., -9.5755e-03,
         -1.9885e-02,  2.5455e-02],
        [ 1.2739e-02,  2.8023e-03, -2.6862e-02,  ..., -2.5689e-02,
          1.7697e-02,  1.4467e-02],
        [-1.7663e-02,  1.2365e-02, -1.7913e-02,  ...,  2.3384e-02,
         -2.8805e-02, -3.8211e-03]])
Gradient - tensor(1.00000e-02 *
       [[-0.1806, -0.1806, -0.1806,  ..., -0.1806, -0.1806, -0.1806],
        [-0.3203, -0.3203, -0.3203,  ..., -0.3203, -0.3203, -0.3203],
        [-0.0751, -0.0751, -0.0751,  ..., -0.0751, -0.0751, -0.0751],
        ...,
        [-0.1858, -0.1858, -0.1858,  ..., -0.1858, -0.1858, -0.1858],
  

In [12]:
print('Updated weights - ', model.fc1.weight)

Updated weights -  Parameter containing:
tensor(1.00000e-02 *
       [[ 0.7058, -2.5516, -0.8287,  ..., -0.4602, -3.0024,  2.6753],
        [ 2.7592, -2.4525, -3.5552,  ...,  0.7054,  2.2210, -1.2570],
        [ 0.0303, -2.6201, -2.0006,  ...,  0.7571, -2.0662, -1.4521],
        ...,
        [-2.4965, -2.6621, -0.7694,  ..., -0.9557, -1.9866,  2.5474],
        [ 1.2721,  0.2785, -2.6880,  ..., -2.5706,  1.7680,  1.4450],
        [-1.7606,  1.2422, -1.7856,  ...,  2.3441, -2.8748, -0.3764]])


### Training for real

Now we'll put this algorithm into a loop so we can go through all the images. This is fairly straightforward. We'll loop through the mini-batches in our dataset, pass the data through the network to calculate the losses, get the gradients, then run the optimizer.

In [13]:
optimizer = optim.SGD(model.parameters(), lr=0.003)

In [14]:
epochs = 3
print_every = 40
steps = 0
for e in range(epochs):
    running_loss = 0
    for images, labels in iter(trainloader):
        steps += 1
        # Flatten MNIST images into a 784 long vector
        images.resize_(images.size()[0], 784)
        
        optimizer.zero_grad()
        
        # Forward and backward passes
        output = model.forward(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        
        if steps % print_every == 0:
            print("Epoch: {}/{}... ".format(e+1, epochs),
                  "Loss: {:.4f}".format(running_loss/print_every))
            
            running_loss = 0

Epoch: 1/3...  Loss: 2.3031
Epoch: 1/3...  Loss: 2.2795
Epoch: 1/3...  Loss: 2.2594
Epoch: 1/3...  Loss: 2.2474
Epoch: 1/3...  Loss: 2.2241
Epoch: 1/3...  Loss: 2.2041
Epoch: 1/3...  Loss: 2.1815
Epoch: 1/3...  Loss: 2.1497
Epoch: 1/3...  Loss: 2.1260
Epoch: 1/3...  Loss: 2.0891
Epoch: 1/3...  Loss: 2.0490
Epoch: 1/3...  Loss: 2.0052
Epoch: 1/3...  Loss: 1.9652
Epoch: 1/3...  Loss: 1.9206
Epoch: 1/3...  Loss: 1.8646
Epoch: 1/3...  Loss: 1.8142
Epoch: 1/3...  Loss: 1.7361
Epoch: 1/3...  Loss: 1.6835
Epoch: 1/3...  Loss: 1.6172
Epoch: 1/3...  Loss: 1.5691
Epoch: 1/3...  Loss: 1.4744
Epoch: 1/3...  Loss: 1.4301
Epoch: 1/3...  Loss: 1.3437
Epoch: 2/3...  Loss: 0.7159
Epoch: 2/3...  Loss: 1.2648
Epoch: 2/3...  Loss: 1.1983
Epoch: 2/3...  Loss: 1.1496
Epoch: 2/3...  Loss: 1.0886
Epoch: 2/3...  Loss: 1.0601
Epoch: 2/3...  Loss: 1.0181
Epoch: 2/3...  Loss: 0.9760
Epoch: 2/3...  Loss: 0.9421
Epoch: 2/3...  Loss: 0.8963
Epoch: 2/3...  Loss: 0.8678
Epoch: 2/3...  Loss: 0.8570
Epoch: 2/3...  Loss:

With the network trained, we can check out it's predictions.

In [ ]:
images, labels = next(iter(trainloader))

img = images[1].view(1, 784)
# Turn off gradients to speed up this part
with torch.no_grad():
    logits = model.forward(img)

# Output of the network are logits, need to take softmax for probabilities
ps = F.softmax(logits, dim=1)
helper.view_classify(img.view(1, 28, 28), ps)

Now our network is brilliant. It can accurately predict the digits in our images.